import {volumes} from './content.js';
const $=s=>document.querySelector(s),reading=$('#reading'),stage=$('.spread-stage'),left=$('#left-page'),right=$('#right-page'),sheet=$('#turn-sheet'),front=$('.turn-front'),back=$('.turn-back');
const br=s=>s.replaceAll('\n','<br>'),num=n=>String(n).padStart(2,'0'),clamp=n=>Math.max(0,Math.min(1,n));
const motif=i=>`<span class="pen-art pen-art-${i}" aria-hidden="true"><span class="art-soft"><i></i></span><span class="art-crisp"><i></i></span></span>`;

const last=volumes.length-1;
const finalMessage=()=>`<div class="final-message"><p>함께 페이지를 넘겨갈<br>사람을 만나는 것.</p><span>on the same page.</span></div>`;
const finalLeft=()=>`<div class="final-half final-left">${finalMessage()}</div><div class="final-brand"><img src="/landing-book/assets/logo/p2-logo-ink.svg" alt="p.2"><span>on the same page.</span></div>`;
const finalRight=()=>`<div class="final-half final-right">${finalMessage()}</div><div class="reading-window final-measure"><div class="reading-copy"></div></div><div class="final-brand mobile-final-brand"><img src="/landing-book/assets/logo/p2-logo-ink.svg" alt="p.2"><span>on the same page.</span></div><div class="final-credits"><a href="mailto:hello@page2.social">문의 ↗</a><small>© 2026 FONDLY STUDIO</small></div>`;
const leftHTML=(v,i)=>i===last?finalLeft():`<div class="page-label">P.2 / ON THE SAME PAGE</div><h2 class="left-title">${br(v.en)}</h2><div class="chapter-drawing">${i<7?motif(i):''}</div><p class="left-note">${br(v.note)}</p><span class="page-number">${num(i*2+1)}</span>`;
const rightHTML=(v,i)=>i===last?finalRight():`<div class="page-label">${num(i+1)} / ${v.label}</div><div class="reading-window"><div class="reading-copy"><div class="mobile-drawing">${i<7?motif(i):''}</div><h2>${br(v.title)}</h2>${v.body??`<h3>${v.desc}</h3><p>${v.copy}</p><blockquote>${br(v.note)}</blockquote><p>${v.detail}</p>`}<p class="turn-prompt">${i===last?'계속 스크롤해 책 덮기 →':'계속 스크롤해 다음 페이지로 →'}</p></div></div><span class="page-number">${num(i*2+2)}</span>`;
function fill(el,i,isLeft){el.innerHTML=(isLeft?leftHTML:rightHTML)(volumes[i],i);el.style.setProperty('--color',volumes[i].cover);el.style.setProperty('--tint',volumes[i].tint)}
const cover=$('#cover'),board=$('#back-cover'),shell=$('#book-shell');
let stops=[],total=0,start=0,opening=0,key='',pending=false,active=-1;
$('#open-cover').onclick=()=>window.scrollTo({top:start+opening+1,behavior:reduced.matches?'instant':'smooth'});
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
function measure(){document.documentElement.style.setProperty('--viewport-height',`${innerHeight}px`);shell.style.width='100%';shell.style.height='100%';opening=innerHeight*1.7;total=0;stops=volumes.map((v,i)=>{fill(right,i,false);const win=right.querySelector('.reading-window'),copy=right.querySelector('.reading-copy');const overflow=Math.max(0,copy.scrollHeight-win.clientHeight),read=Math.max(innerHeight*.85,overflow+innerHeight*.25),turn=i<last?innerHeight*.75:0;const item={start:total,read,turn,overflow};total+=read+turn;return item});reading.style.height=`${opening+total+innerHeight*1.2+stage.offsetHeight}px`;start=reading.getBoundingClientRect().top+scrollY;key='';draw()}
function draw(){pending=false;if(!stops.length)return;const raw=scrollY-start,intro=clamp(raw/opening),zoom=clamp(intro/.58),z=zoom*zoom*(3-2*zoom),progress=clamp((intro-.48)/.52),ease=progress*progress*(3-2*progress);const scale=reduced.matches?1:.84+.16*z;shell.style.transform=`translate(-50%,-50%) scale(${scale})`;$('.outside-edition').style.opacity=String(1-clamp(zoom/.7));$('#spread').style.visibility=intro<.48?'hidden':'visible';$('.reader-nav').style.visibility=intro<.48?'hidden':'visible';cover.style.transform=reduced.matches?'none':`rotateY(${-110*ease}deg)`;cover.style.opacity=reduced.matches?String(1-progress):'1';cover.style.visibility=progress>=1?'hidden':'visible';cover.inert=progress>.12;cover.style.setProperty('--cover-shade',String(Math.sin(progress*Math.PI)*.22));stage.querySelector('.reader-nav').inert=progress<1;const close=clamp((raw-opening-total)/(innerHeight*1.2));board.style.transform=reduced.matches?'none':`rotateY(${100*(1-close*close*(3-2*close))}deg)`;board.style.opacity=reduced.matches?String(close):'1';board.style.visibility=close===0?'hidden':'visible';board.inert=close<.95;const y=Math.max(0,Math.min(total,raw-opening));let i=stops.findIndex((s,j)=>j===last||y<stops[j+1].start);const s=stops[i],local=y-s.start,t=s.turn?clamp((local-s.read)/s.turn):0,turning=t>0&&i<last,k=`${i}-${turning}`;
if(k!==key){fill(left,i,true);fill(right,turning?i+1:i,false);if(turning){fill(front,i,false);fill(back,i+1,true);front.querySelector('.reading-copy').style.transform=`translateY(${-s.overflow}px)`}key=k}
if(turning){const eased=t*t*(3-2*t);sheet.style.display=reduced.matches?'none':'block';sheet.style.transform=`rotateY(${-180*eased}deg)`;sheet.style.setProperty('--shade',String(Math.sin(Math.PI*t)*.2));sheet.style.filter='';sheet.style.boxShadow=`${Math.sin(Math.PI*t)*22}px 4px 35px #291b2426`;if(reduced.matches&&t>.5)fill(left,i+1,true)}else{sheet.style.display='none';right.querySelector('.reading-copy').style.transform=`translateY(${-s.overflow*clamp(local/s.read)}px)`}
const current=turning&&t>.5?i+1:i;if(active!==current){active=current;document.querySelectorAll('#chapter-nav button').forEach((b,j)=>{j===current?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')});$('#reading-status').textContent=`${num(current+1)} / ${num(volumes.length)}`;$('#prev').disabled=current===0;}
}
function go(i){if(i>last){window.scrollTo({top:start+opening+total+innerHeight*1.2,behavior:reduced.matches?'instant':'smooth'});return}window.scrollTo({top:start+opening+stops[Math.max(0,i)].start+1,behavior:reduced.matches?'instant':'smooth'})}
volumes.forEach((v,i)=>{const b=document.createElement('button');b.textContent=num(i+1);b.setAttribute('aria-label',`${i+1}장 ${v.short}`);b.addEventListener('click',()=>go(i));$('#chapter-nav').append(b)});$('#prev').onclick=()=>go(active-1);$('#next').onclick=()=>go(active+1);
addEventListener('scroll',()=>{if(!pending){pending=true;requestAnimationFrame(draw)}},{passive:true});let resize;addEventListener('resize',()=>{clearTimeout(resize);resize=setTimeout(measure,150)});measure();document.fonts.ready.then(measure);

$('#return-cover').onclick=()=>window.scrollTo({top:0,behavior:reduced.matches?'instant':'smooth'});
$('.back-invite').onclick=e=>{e.preventDefault();go(5)};
reading.addEventListener('toggle',e=>{if(e.target.tagName==='DETAILS'){const expanded=e.target.open;const selector=e.target.querySelector('summary')?.textContent;if(expanded){e.target.querySelector('p').style.display='block'}requestAnimationFrame(()=>{const i=active;if(i<0)return;const win=right.querySelector('.reading-window'),copy=right.querySelector('.reading-copy');const delta=Math.max(0,copy.scrollHeight-win.clientHeight)-stops[i].overflow;stops[i].overflow+=delta;stops[i].read+=delta;for(let j=i+1;j<stops.length;j++)stops[j].start+=delta;total+=delta;reading.style.height=`${opening+total+innerHeight*1.2+stage.offsetHeight}px`;draw()})}},true);
